spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookshelf
    username: user
    password: password
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:liquibase/changelog.xml
